# pull official base image
FROM node:16-alpine3.14

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

#set the ownership of the cache folder
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

# add app
COPY ./src ./

# start app
CMD ["npm", "start"]