name: Docker Image CI

on:
  push:
    branches:
      - main
      - develop
      - migrate-to-typescript
  pull_request:
    branches:
      - main
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --target production --tag my-image-name:$(date +%s)
